# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
- linux
- osx
- Windows
julia:
- 1.5
- nightly
matrix:
allow_failures:
    - julia: nightly
fast_finish: true
notifications:
email: false
after_success:
- julia -e 'using Pkg; cd(Pkg.dir("QuEST_jl")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'